---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: service-registry-tls
  labels:
    strimzi.io/cluster: my-kafka
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      # Group Id to consume information for the different topics used by the Service Registry.
      # Name equals to metadata.name property in ApicurioRegistry object
      - resource:
          type: group
          name: '*'
          patternType: literal
        operation: Read
      # Rules for the kafkasql-journal topic
      - resource:
          type: topic
          name: kafkasql-journal
          patternType: literal
        operation: All
