---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: apicurio-registry
  namespace: operators
spec:
  channel: 2.x
  name: apicurio-registry
  source: operatorhubio-catalog
  sourceNamespace: olm
  startingCSV: apicurio-registry-operator.v1.0.0-v2.0.0.final
