---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: apicurio-registry
  namespace: amq-streams-demo
spec:
  channel: 2.x
  installPlanApproval: Automatic
  name: apicurio-registry
  source: community-operators
  sourceNamespace: openshift-marketplace
