# Default values for kafka-clients-quarkus-sample-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

name: kafka-clients-quarkus-sample
nameOverride: ""
fullnameOverride: ""

# Build Configuration

buildConfig:
  enabled: true

git:
  url: https://github.com/rmarting/kafka-clients-quarkus-sample.git

# Application Deployment

replicaCount: 1

image:
  repository: amq-streams-demo
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""


podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

nodeSelector: {}

tolerations: []

affinity: {}

# Application Resources

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# Application Service

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

# Application OpenShift Route

route:
  enabled: true

# Application Kubernetes Ingress

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

# Application Horizontal Pod Autoscaler

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
