apiVersion: registry.apicur.io/v1
kind: ApicurioRegistry
metadata:
  name: service-registry
spec:
  configuration:
    persistence: "kafkasql"
    kafkasql:
      bootstrapServers: "my-kafka-kafka-bootstrap:9093"
      security:
        scram:
          mechanism: SCRAM-SHA-512
          user: service-registry-scram
          passwordSecretName: service-registry-scram
          truststoreSecretName: my-kafka-cluster-ca-cert
    ui:
      readOnly: false
    logLevel: INFO
  deployment:
    replicas: 1
