---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: {{ .Values.kafka.name | quote }}
    {{- include "kafka-clients-quarkus-sample-eda-chart.labels" . | nindent 4 }}    
  name: "messages"
spec:
  partitions: {{ .Values.kafkaTopic.partitions }}
  replicas: {{ .Values.kafkaTopic.replicas }}
  config:
    min.insync.replicas: "{{ .Values.kafkaTopic.minInsync }}"
    retention.ms: "7200000"
    segment.bytes: "1073741824"
