apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-clients-quarkus-sample-app-pro
  namespace: tools-ci-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io  
spec:
  project: kafka-clients-quarkus
  source:
    repoURL: 'https://github.com/rmarting/kafka-clients-quarkus-sample.git'
    targetRevision: HEAD
    path: charts/app-chart
    helm:
      parameters:
        - name: image.repository
          value: image-registry.openshift-image-registry.svc:5000/amq-streams-dev
        - name: buildConfig.enabled
          value: 'false'
  destination:
    namespace: amq-streams-pro
    name: ocp-pro
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true
