# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: 👷 Pull Request CI pipeline 👷

# This section allows the workflow to create a Release
# https://github.com/softprops/action-gh-release/issues/236#issuecomment-1150530128
permissions:
  checks: write
  contents: write
  pull-requests: write

# This section ensures that new pushes cancel current executions of the workflow
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'argocd/**'
      - 'img/**'
      - 'LICENSE'
      - '*.md'    

env:
  JAVA_VERSION: "17"
    
jobs:
  setup:
    runs-on: ubuntu-latest
    name: Get Application Version
    outputs:
      app_version: ${{ steps.get_app_version.outputs.version }}
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'adopt'

      - name: Get version from Maven project
        id: get_app_version
        run: |
          APP_VERSION=$(./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "Application Version: $APP_VERSION"
          echo "version=$APP_VERSION" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    name: "Compile"
    needs:
      - setup
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'adopt'

      - name: Build with Maven
        run: |
          echo "Building version ${{ needs.setup.outputs.app_version }}"
          ./mvnw -B package --file pom.xml

      #- name: Official SonarQube Scan
      #  uses: SonarSource/sonarqube-scan-action@v1.0.0

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: target/surefire-reports/**/*.xml

  build-jvm:
    runs-on: ubuntu-latest
    needs:
      - setup
      - build
    name: "Build Artifact"
    steps:
      - name: "Checkout the code"
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'adopt'
        
      - name: "Build executable"
        run: ./mvnw install --no-transfer-progress -DskipTests

      - name: "Upload executable"
        uses: actions/upload-artifact@v3
        with:
          name: executable
          path: target/quarkus-app/*
